- name: clean up custom sources
  become: yes
  shell: rm /etc/apt/sources.list.d/*.list*
  when: clean_apt_sources | bool
  notify:
    - upgrade packages

- name: install packages for development
  become: yes
  apt:
    pkg: "{{ item }}"
  with_items: "{{ apt_packages.dev }}"
  notify:
    - upgrade packages

- name: install packages for building
  become: yes
  apt:
    pkg: "{{ item }}"
  with_items: "{{ apt_packages.build }}"
  notify:
    - upgrade packages
  when: not (dev_minimal|bool)

- name: install packages with extra tools
  become: yes
  apt:
    pkg: "{{ item }}"
  with_items: "{{ apt_packages.tools }}"
  notify:
    - upgrade packages
  when: not (dev_minimal|bool)
