- name: ensure local bin folder exists
  file:
    path: "{{ansible_user_dir}}/.local/bin"
    state: directory

- name: get latest jq release
  uri:
    url: https://api.github.com/repos/stedolan/jq/releases/latest
  register: jq_latest

- name: download latest jq
  get_url:
    url: "{{jq_latest.json.assets | selectattr('name', 'search', 'linux64')| map(attribute='browser_download_url')|first}}"
    dest: "{{ansible_user_dir}}/.local/bin/jq"
    mode: "u+x"
    force: yes

- name: get latest starship release
  uri:
    url: https://api.github.com/repos/starship/starship/releases/latest
  register: starship_latest

- name: download starship
  become: yes
  unarchive:
    remote_src: yes
    src: "{{starship_latest.json.assets | selectattr('name', 'search', 'x86_64-unknown-linux-musl')| map(attribute='browser_download_url')|first}}"
    dest: /usr/local/bin/
    keep_newer: yes

#- name: get latest fzf
#  uri:
#    url: https://api.github.com/repos/junegunn/fzf-bin/releases/latest
#  register: fzf_latest

#- name: download latest fzf
#  unarchive:
#    remote_src: yes
#    src: "{{ fzf_latest.json.assets | selectattr('name', 'search', 'linux_amd64')| map(attribute='browser_download_url')|first}}"
#    dest: "{{ ansible_user_dir }}/.local/bin/"
#    keep_newer: yes
#    extra_opts:
#      - "fzf"
