- name: ensure local bin folder exists
  file:
    path: "{{ local_bin_dir }}"
    state: directory

- name: get latest jq release
  uri:
    url: https://api.github.com/repos/stedolan/jq/releases/latest
  register: jq_latest

- name: download latest jq
  get_url:
    url: "{{jq_latest.json.assets | selectattr('name', 'search', 'linux64')| map(attribute='browser_download_url')|first}}"
    dest: "{{ local_bin_dir }}/jq"
    mode: "u+x"
    force: yes

- name: get latest starship release
  uri:
    url: https://api.github.com/repos/starship/starship/releases/latest
  register: starship_latest

- name: download starship
  become: yes
  unarchive:
    remote_src: yes
    src: "{{starship_latest.json.assets | selectattr('name', 'search', 'x86_64-unknown-linux-musl')| map(attribute='browser_download_url')|first}}"
    dest: /usr/local/bin/
    keep_newer: yes

- name: get latest k9s release
  tags:
    - k9s
  uri:
    url: https://api.github.com/repos/derailed/k9s/releases/latest
  register: k9s_latest

- name: install latest k9s release
  tags:
    - k9s
  unarchive:
    remote_src: yes
    src: "{{ k9s_latest.json.assets | selectattr('name', 'search', 'Linux_amd64')| map(attribute='browser_download_url')|first}}"
    dest: "{{ local_bin_dir }}/"
    keep_newer: yes
    extra_opts:
      - "k9s"

- name: create config dir for k9s
  tags:
    - k9s
  file:
    path: "{{ userhome }}/.config/k9s"
    state: directory

- name: install my solarized colorscheme for k9s
  tags:
    - k9s
  get_url:
    url: https://raw.githubusercontent.com/pshchelo/dotfiles/master/colors/k9s-solarized-dark.yml
    dest: "{{ userhome }}/.config/k9s/skin.yml"
    force: yes

#- name: get latest fzf
#  uri:
#    url: https://api.github.com/repos/junegunn/fzf-bin/releases/latest
#  register: fzf_latest

#- name: download latest fzf
#  unarchive:
#    remote_src: yes
#    src: "{{ fzf_latest.json.assets | selectattr('name', 'search', 'linux_amd64')| map(attribute='browser_download_url')|first}}"
#    dest: "{{ local_bin_dir }}/"
#    keep_newer: yes
#    extra_opts:
#      - "fzf"
