- name: create dotfiles by cloning
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    accept_hostkey: yes
    update: no

- name: set push url for dotfiles repo
  git_config:
    repo: "{{ dotfiles_dir }}"
    scope: "local"
    name: "remote.origin.pushurl"
    value: "{{ dotfiles_repo_push }}"

- name: backup some files
  shell: mv {{ item }} {{ item }}.orig
  args:
    creates: "{{ item }}.orig"
    removes: "{{ item }}"
  with_items: "{{ files_to_backup }}"

- name: create some folders
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ dirs_to_create }}"

- name: make links
  file:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    state: link
  with_items: "{{ links_to_create }}"
