- name: copy ssh keys
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: "{{item.mode}}"
  with_items: "{{ ssh_keys }}"
  when: copy_keys | bool

- include: apt.yaml
  when: ansible_os_family == 'Debian'

- include: python.yaml

- include: dotfiles.yaml

- include: binaries.yaml

- include: vim.yaml
