- name: copy ssh keys
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: "{{item.mode}}"
  with_items: "{{ ssh_keys }}"
  when: copy_keys | bool

- include: apt.yaml
  when: ansible_os_family == 'Debian'
  tags:
  - pkgs

- include: python.yaml
  tags:
  - python

- include: dotfiles.yaml
  tags:
  - dotfiles

- include: binaries.yaml
  tags:
  - bin

- include: vim.yaml
  tags:
  - vim
