- name: copy ssh keys
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: "{{item.mode}}"
  with_items: "{{ ssh_keys }}"
  when: copy_keys | bool

- import_tasks: apt.yaml
  when: ansible_os_family == 'Debian'
  tags:
  - pkgs

- import_tasks: python.yaml
  tags:
  - python

- import_tasks: dotfiles.yaml
  tags:
  - dotfiles

- import_tasks: binaries.yaml
  tags:
  - bin

- import_tasks: vim.yaml
  tags:
  - vim
