- name: fetch pip bootstrapper script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    force: yes

- name: install pip
  become: true
  command: "{{ hostvars[inventory_hostname].ansible_python_interpreter }} /tmp/get-pip.py"

- name: install python packages from PyPI to userspace
  pip:
    name: "{{ item }}"
    extra_args: --user
  with_items: "{{ pip_pkgs }}"
  when: not (dev_minimal|bool)
