- name: upgrade local pip
  command: "{{ hostvars[inventory_hostname].ansible_python_interpreter }} -m pip install -U pip"
  become: true

- name: install python packages from PyPI to userspace
  pip:
    name: "{{ pip_pkgs }}"
    extra_args: --user
  when: not (dev_minimal|bool)
