- name: install packages for py3
  become: yes
  apt:
    pkg: "{{ apt_packages_py }}"

# devstack downgrades pip itself if needed
- name: upgrade local pip
  become: yes
  pip:
    executable: pip3
    name: pip
    state: latest

- name: install python packages from PyPI to userspace
  become: yes
  pip:
    executable: pip3
    name: "{{ pip_pkgs }}"
  when: not (dev_minimal|bool)
