- name: install packages for py3
  become: yes
  apt:
    pkg: "{{ apt_packages_py }}"

- name: install python packages from PyPI to userspace
  become: yes
  pip:
    executable: pip3
    name: "{{ pip_pkgs }}"
  when: not (dev_minimal|bool)
