- name: make dir for vim-plug
  file:
    path: "{{ userhome }}/.vim/autoload"
    state: directory

- name: make a link to vim config
  file:
    path: "{{ userhome }}/.vim/vimrc"
    src: "{{ dotfiles_dir }}/vim/vimrc"
    state: link

- name: install/update vim-plug
  get_url:
    dest: "{{ userhome }}/.vim/autoload/plug.vim"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    force: yes

- name: install all vim plugins
  command: vim +PlugUpdate +qall
  args:
    creates: "{{ userhome }}/.vim/plugged"
