#!/usr/bin/env sh
# Define custom personal aliases

# open files from terminal with GUI default application
alias xopen=xdg-open

# change directory two levels up
alias ...="cd ../.."

# copy command for big files, with progress indication
alias longcp='rsync --progress -ah'

# alias for running single Python unit tests with testtools
alias ttools='python -m testtools.run'

# attach to running tmux or start a new one if absent
alias tmx='tmux -2 a || tmux -2'

# terminal pastebin
# use as "cat somefile | tb"
alias tb='nc termbin.com 9999'

# openstack CLI as devstack user
alias osdemo='openstack --os-cloud devstack'

# openstack CLI as devstack admin
alias osadmin='openstack --os-cloud devstack-admin'
