#!/usr/bin/env sh
# Define custom personal aliases

# open files from terminal with GUI default application
alias xopen=xdg-open

# change directory two levels up
alias ...="cd ../.."

# go to the previous directory
alias back="cd -"

# copy command for big files, with progress indication
alias longcp='rsync --progress -ah'

# alias for running single Python unit tests with testtools
alias ttools='python -m testtools.run'
