#!/usr/bin/env sh
# Define custom personal aliases

# open files from terminal with GUI default application
alias xopen=xdg-open

# change directory two levels up
alias ...="cd ../.."

# go to the previous directory
alias back="cd -"

# copy command for big files, with progress indication
alias longcp='rsync --progress -ah'

# alias for running single Python unit tests with testtools
alias ttools='python -m testtools.run'

# attach to running tmux or start a new one if absent
alias tmx='tmux a || tmux'

# terminal pastebin
# use as "cat somefile | tb"
alias tb='nc termbin.com 9999'

# openstack CLI
alias os=openstack
