#!/usr/bin/env bash
# Clean _P_ython _p_roject versioned by git
GIT_ROOT="$(git rev-parse --show-toplevel)"
# delete leftovers of git merges
find "$GIT_ROOT" -type f -name "*.orig" -delete
# delete Python compiled files
find "$GIT_ROOT" -type f -name "*.pyc" -delete
# delete empty folders outside .git folder
find "$GIT_ROOT" -type d -not -path "./.git/*" -empty -delete

if [[ $1 = "-a" ]]; then
    rm -rf "$GIT_ROOT/.tox/"
    rm -rf "$GIT_ROOT/.stestr/"
    rm -rf "$GIT_ROOT/.testr/"
fi
