- name: List IPtables rules
  become: yes
  shell: iptables -L
  register: iptables_rules
  always_run: true
  changed_when: false
  tags: iptables

- name: Set IPtables outbound access from internal networks
  become: yes
  shell:  "iptables -I FORWARD -m state -d {{ item.cidr }} --state NEW,RELATED,ESTABLISHED -j ACCEPT -m comment --comment '{{ item.comment }}'"
  when: iptables_rules.stdout.find(item.comment) == -1
  with_items: "{{ outbound_access }}"
  tags: iptables

- name: list vms on host
  virt:
    command: list_vms
  register: vmlist

- name: start all devstack vms
  virt:
    name: "{{ item }}"
    state: running
  when: "{{ 'devstack' in item }}"
  with_items: "{{ vmlist.list_vms }}"
