username: "{{ ansible_user_id }}"
userhome: "{{ ansible_user_dir }}"
useremail: pshchelokovskyy@mirantis.com
dotfiles_dir: "{{ userhome }}"
stackdev_dir: "{{ userhome }}/stackdev"
devstack_dir: "/opt/stack"
