- name: add ppa repos
  become: true
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ ppa_repos }}"
  when: ansible_distribution == 'Ubuntu'

- name: install packages for development
  become: true
  apt:
    pkg: "{{ item }}"
  with_items: "{{ apt_packages }}"


