- name: fetch pip bootstrapper script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    force: yes

- name: install pip
  become: true
  command: python /tmp/get-pip.py

- name: install global python packages
  become: true
  pip:
    name: "{{ item }}"
  with_items: "{{ global_python }}"


