apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- components.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: metrics-server
  path: metrics-server-insecure.yaml
