- name: add extra apt keys
  become: yes
  apt_key:
    id: "{{ item.name }}"
    url: "{{ item.url }}"
    state: present
  with_items: "{{ apt_keys_desktop }}"

- name: setup extra repos
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
    mode: 644
  with_items: "{{ apt_repos_desktop }}"
  notify:
    - upgrade packages

- name: install system packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items: "{{ apt_pkgs_desktop }}"
