#!/usr/bin/env bash
# syncronize directory on Mac to/from remote Linux machine
SYNC_TO=0
SYNC_FROM=0
RSYNC_ARGS=""
while getopts ':ht:f:md' arg; do
    case ${arg} in
        h)
            echo "Usage: $(basename "$0") [-h] [-t | -f ] [-m] [-d] <remote server>"
            echo "Syncronize directory on MacOS with remote Linux server using rsync"
            echo "Copy [-t]o or [-f]rom <remote server> dir of the 'same' path as current dir on Mac"
            echo "  -h            Display this help message"
            echo "  -t <server>   Sync TO remote server"
            echo "  -f <server>   Sync FROM remote server"
            echo "  -m            Mirror (delete files on destination that don't exist on source)"
            echo "  -d            Dry run (show what would be done without actually doing it)"
            exit 0
            ;;
        t)
            remote_server="${OPTARG}"
            SYNC_TO=1
            ;;
        f)
            remote_server="${OPTARG}"
            SYNC_FROM=1
            ;;
        m)
            RSYNC_ARGS+=" --delete" ;;
        d)
            RSYNC_ARGS+=" --dry-run" ;;
        \?)
            echo "Invalid option: -${OPTARG}" >&2
            exit 1
            ;;
        :)
            echo "Option -${OPTARG} requires an argument." >&2
            exit 1
            ;;
    esac
done
if [ $SYNC_TO = $SYNC_FROM ]; then
    echo "Error: You must specify either -t (to) or -f (from), but not both."
    exit 1
fi
local_path="${PWD}"
remote_path="${remote_server}:${PWD//Users/home/}"
if [[ $SYNC_FROM = 1 ]]; then
    src=$remote_path
    dst=$local_path
else
    dst=$remote_path
    src=$local_path
fi
# shellcheck disable=SC2086 # word-split on RSYNC_ARGS is intended
rsync -PaSh $RSYNC_ARGS "${src}/" "${dst}"
