#!/usr/bin/env bash
HLP_MSG="Usage: $0 (u[p]|d[own]|h[elp]) [connection]"
action=$1
conn=${2:-Cato}

function vpn_up {
    if [ "$conn" = "Cato" ]; then
        catovpn_up
    else
        openvpn_up
    fi
}

function vpn_down {
    if [ "$conn" = "Cato" ]; then
        catovpn_down
    else
        openvpn_down
    fi
}

function catovpn_up {
    cato-sdp start --use-systemd-resolv --route 172.16.0.0/12 --metric 1000
    sudo ip route add 172.16.0.0/12 dev tun0
}

function catovpn_down {
    sudo cato-sdp status | grep "^Cato client is disconnected" > /dev/null || cato-sdp stop
}

function openvpn_up {
if [ -z  "$(nmcli connection show --active $conn)" ]; then
    nmcli connection up "$conn"
fi
}

function openvpn_down {
if [ -n "$(nmcli connection show --active $conn)" ]; then
    nmcli connection down "$conn"
fi
}

case $action in
    up|u)
        vpn_up
        ;;
    down|d)
        vpn_down
        ;;
    help|h)
        echo "$HLP_MSG"
        exit 0
        ;;
    *)
        echo "$HLP_MSG"
        exit 1
        ;;
esac
