---
- hosts: dsvm
  vars:
    dev_minimal: true
    bifrost_git_repo: "https://opendev.org/openstack/bifrost.git"
    bifrost_git_ref: master
  roles:
    - hostname
    - devhost
  post_tasks:
  - name: clone bifrost
    git:
      repo: "{{ bifrost_git_repo }}"
      dest: "{{ ansible_user_dir }}/bifrost"
      version: "{{ bifrost_git_ref }}"
