all:
  children:
    work-vms:
      hosts:
        dsvm1-kvm-work:
        dsvm2-kvm-work:
        kaas-kvm-work:
    hypervisors:
      hosts:
        kvm-work:
    kaas:
      vars:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ansible_ssh_private_key_file: ~/.ssh/aio_rsa
        ansible_user: ubuntu
        clean_apt_sources: true
