all:
  children:
    work_vms:
      hosts:
        dsvm1-kvm-work:
        dsvm2-kvm-work:
        dsvm3-kvm-work:
    hypervisors:
      hosts:
        kvm-work:
    aio:
      vars:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ansible_ssh_private_key_file: ~/.ssh/aio_rsa
        ansible_user: ubuntu
      children:
