ungrouped:
  hosts:
    localhost:
      ansible_connection: local
home:
  hosts:
    swthm:
    cube:
work:
  hosts:
    workvm:
dsvm:
  hosts:
    devstack:
    pshchelo-devstack:
    pshchelo-devstack-compute:
