---
- hosts: hypervisors
  vars:
  tasks:
    # NOTE this is a hack until I figure out how to add it permamently
  - name: add local libvirt DNS to resolve.conf
    become: yes
    blockinfile:
      path: /etc/resolv.conf
      block: |
        nameserver 192.168.100.1
        search kvm.work
      insertbefore: BOF
