---
- hosts: hypervisors
  vars:
    outbound_access:
    - cidr: "192.168.100.0/24"
      comment: "outbound access for virsh default network"
  tasks:
  - name: set iptables for VMs outbound access
    become: yes
    iptables:
      state: present
      chain: FORWARD
      destination: "{{ item.cidr }}"
      jump: ACCEPT
      ctstate:
        - NEW
        - RELATED
        - ESTABLISHED
      comment: "{{ item.comment }}"
    with_items: "{{ outbound_access }}"
