- name: copy kubeconfig
  become: true
  copy:
    src: /root/.kube
    dest: "{{ ansible_user_dir }}/.kube"
    remote_src: true
    owner: "{{ ansible_user_id }}"

- name: ensure bash completion folder exists
  file:
    path: "{{ ansible_user_dir }}/.local/share/bash-completion/completions"
    state: directory

- name: create kubectl bash auto-completion if missing
  shell: "kubectl completion bash > {{ ansible_user_dir }}/.local/share/bash-completion/completions/kubectl"
  args:
    creates: "{{ ansible_user_dir }}/.local/share/bash-completion/completions/kubectl"

- name: clone osh-operator
  git:
    repo: ssh://pshchelokovskyy@gerrit.mcp.mirantis.com:29418/mcp/osh-operator
    dest: "{{ ansible_user_dir }}/osh-operator"
    accept_hostkey: true

- name: install osh-operator dev dependencies
  become: yes
  apt:
    pkg:
      - tox
      - python3.7

- name: get k9s releases
  uri:
    url: https://api.github.com/repos/derailed/k9s/releases
  register: k9s_releases

- name: get latest k9s tag
  set_fact:
    k9s_tag_latest: "{{ k9s_releases.json | map(attribute='tag_name') | max }}"

# TODO: pull URL of the latest Linux_x86_64 artifact from JSON response
# jq '. | max_by(.tag_name) | .assets | map(select(.name | contains("Linux_x86_64"))) | .[0].browser_download_url'
#- name: get artefact url
#  set_fact:
#    k9s_url: "{{ k9s_releases.json | max(attribute='tag_name') | attr('assets') | selectattr('name', 'match', 'Linux_x86_64') | 0.browser_download_url }}"

- name: install latest k9s release
  unarchive:
    remote_src: yes
    src: https://github.com/derailed/k9s/releases/download/{{ k9s_tag_latest }}/k9s_{{ k9s_tag_latest }}_Linux_x86_64.tar.gz
    dest: "{{ ansible_user_dir }}/.local/bin }}"
    keep_newer: yes
    extra_opts:
      - "k9s"
