- name: copy kubeconfig
  become: true
  copy:
    src: /root/.kube
    dest: "{{ ansible_user_dir }}/.kube"
    remote_src: true
    owner: "{{ ansible_user_id }}"

- name: ensure bash completion folder exists
  file:
    path: "{{ ansible_user_dir }}/.local/share/bash-completion/completions"
    state: directory

- name: create kubectl bash auto-completion if missing
  shell: "kubectl completion bash > {{ ansible_user_dir }}/.local/share/bash-completion/completions/kubectl"
  args:
    creates: "{{ ansible_user_dir }}/.local/share/bash-completion/completions/kubectl"

- name: clone osh-operator
  git:
    repo: ssh://pshchelokovskyy@gerrit.mcp.mirantis.com:29418/mcp/osh-operator
    dest: "{{ ansible_user_dir }}/osh-operator"
    accept_hostkey: true

- name: install osh-operator dev dependencies
  become: yes
  apt:
    pkg:
      - tox
      - python3.7

# TODO: use native ansible modules instead of curl
# TODO: find programmatic way to donwload the latest (pre-)release version
- name: install k9s from GitHub release
  shell: "curl -sL https://github.com/derailed/k9s/releases/download/0.9.2/k9s_0.9.2_Linux_x86_64.tar.gz | tar xz k9s"
  args:
    chdir: "{{ ansible_user_dir }}/.local/bin"
    creates: "{{ ansible_user_dir }}/.local/bin/k9s"
    warn: false
#  unarchive:
#    remote_src: yes
#    src: https://github.com/derailed/k9s/releases/download/0.9.2/k9s_0.9.2_Linux_x86_64.tar.gz
#    dest: "{{ ansible_user_dir }}/.local/bin }}"
#    creates: "{{ ansible_user_dir }}/.local/bin/k9s }}"
