---
- name: pre-install libvirt
  become: yes
  package:
    name: "{{ item }}"
  with_items: "{{ libvirt_pkgs }}"

- name: add myself to libvirtd group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: "{{ libvirt_group }}"

- name: clone bifrost
  git:
    repo: "{{ bifrost_git_repo }}"
    dest: "{{ ansible_user_dir }}/bifrost"
    version: master
