- name: copy kubeconfig
  become: yes
  copy:
    src: /root/.kube
    dest: "{{ ansible_user_dir }}"
    remote_src: true
    owner: "{{ ansible_user_id }}"

- name: ensure bash completion folder exists
  file:
    path: "{{ ansible_user_dir }}/.local/share/bash-completion/completions"
    state: directory

- name: create kubectl bash auto-completion if missing
  shell: "kubectl completion bash > {{ ansible_user_dir }}/.local/share/bash-completion/completions/kubectl"
  args:
    creates: "{{ ansible_user_dir }}/.local/share/bash-completion/completions/kubectl"

- name: clone openstack-controller
  git:
    repo: ssh://pshchelokovskyy@gerrit.mcp.mirantis.com:29418/mcp/openstack-controller
    dest: "{{ ansible_user_dir }}/openstack-controller"
    accept_hostkey: true

- name: install openstack-controller dependencies
  become: yes
  apt:
    pkg:
      - python3.7-dev

- name: install latest tox
  become: yes
  pip:
    name: tox
    state: latest

- name: get latest k9s release
  uri:
    url: https://api.github.com/repos/derailed/k9s/releases/latest
  register: k9s_latest

- name: install latest k9s release
  unarchive:
    remote_src: yes
    src: "{{ k9s_latest.json.assets | selectattr('name', 'eq', 'k9s_Linux_x86_64.tar.gz')| map(attribute='browser_download_url')|first}}"
    dest: "{{ ansible_user_dir }}/.local/bin/"
    keep_newer: yes
    extra_opts:
      - "k9s"

- name: create config dir for k9s
  file:
    path: "{{ ansible_user_dir }}/.k9s"
    state: directory

- name: install my solarized colorscheme for k9s
  get_url:
    url: https://raw.githubusercontent.com/pshchelo/dotfiles/master/colors/k9s-solarized-dark.yml
    dest: "{{ ansible_user_dir }}/.k9s/skin.yml"
    force: yes

- name: get latest metrics-server tag
  uri:
    url: https://api.github.com/repos/kubernetes-sigs/metrics-server/releases/latest
  register: metrics_server_latest

- name: clone metrics-server
  git:
    repo: https://github.com/kubernetes-sigs/metrics-server
    dest: "{{ ansible_user_dir }}/metrics-server"
    depth: 1
    version: "{{ metrics_server_latest.json.tag_name }}"

- name: copy kustomizations for metrics-server
  copy:
    dest: "{{ ansible_user_dir}}/metrics-server/deploy/1.8+/{{ item }}"
    src: "{{ item }}"
  with_items:
    - dev-insecure.yaml
    - kustomization.yaml
# NOTE(pas-ha) deploy via "kubectl apply -k ~/metrics-server/deploy/1.8+/"
